# Generated by Django 3.1.7 on 2021-02-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team_members',
            field=models.ManyToManyField(to='main_app.Team_Member'),
        ),
    ]
