# Generated by Django 3.1.7 on 2021-02-24 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_task_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
    ]
