# Generated by Django 3.1.7 on 2021-02-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210224_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='team_member',
            name='role',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
