# Generated by Django 3.1.7 on 2021-02-26 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_team_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.team_member')),
            ],
        ),
    ]
